 - hosts: all
   tasks:
     - name: Install dependencies
       package:
         name: ['just', 'python3-pyyaml']
         state: present
       become: yes
     - name: Validate manifests and scripts syntax
       ansible.builtin.command:
         chdir: "{{ zuul.project.src_dir }}"
         cmd: just validate
